name: Publish to NPM

on:
  push:
    paths:
      - 'index.js'
      - 'bin.js'
      - '.github/workflows/publish.yml'
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: NPM Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Update versions
        run: |
          pnpm run auto-version

      - name: Prepare git and update version
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "tags: updated tags" -a

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Publish to NPM # OIDC authentication
        run: pnpm publish --access public --no-git-checks
